name: Build & Deploy

on:
  push:
    tags:
      - 'v*'  # Trigger workflow only on version tags (e.g., v1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Updated to v2
      with:
        install: true
      continue-on-error: false  # Fail if setup fails

    - name: Extract version from tag
      id: extract_tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        echo "VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Updated to v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      continue-on-error: false  # Fail if authentication fails

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v3  # Updated to v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64  # Specify multiple architectures
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/opi-led-server:latest
          ${{ secrets.DOCKER_USERNAME }}/opi-led-server:${{ env.VERSION }}
      continue-on-error: false  # Fail if build or push fails

    - name: Log out from Docker Hub
      run: docker logout

    - name: Log in to GitHub Container Registry (GHCR)
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Explicitly use GITHUB_TOKEN
      continue-on-error: false  # Fail if authentication fails

    - name: Build and push Docker image to GHCR
      uses: docker/build-push-action@v3  # Updated to v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64  # Specify multiple architectures
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/opi-led-server:latest
          ghcr.io/${{ github.repository_owner }}/opi-led-server:${{ env.VERSION }}
      continue-on-error: false  # Fail if build or push fails

    - name: Log out from GHCR
      run: docker logout